[project]
name = "wflow"
version = "0.1.0"
description = "Add a short description here"
authors = ["Michael O'Hanrahan <104068149+michaelohanrahan@users.noreply.github.com>"]
channels = ["conda-forge", "bioconda", "pip"]
platforms = ["win-64", "linux-64"]

[system-requirements]
linux = "4.18"

[tasks]

[dependencies]
cookiecutter = ">=2.6.0,<2.7"
jinja2-time = ">=0.2.0,<0.3"
dvc = ">=3.48.2"
snakemake = ">=8.10.6,<8.11"
scipy = ">=1.13.0,<1.14"
geopandas = ">=0.14.3,<0.15"
jupyter = ">=1.0.0,<1.1"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.8.4,<3.9"
icecream = ">=2.1.3,<2.2"
graphviz = ">=9.0.0,<9.1"
pyet = ">=1.3.1,<2"
hydromt = ">0.9.4,<0.11"
hydromt_wflow = ">0.5.0"
numpy = "1.26.4.*"
snakemake-executor-plugin-cluster-generic = ">=1.0.9,<2"
dask = ">=2024.9.1,<2025"
distributed = ">=2024.9.1,<2025"
cartopy = ">=0.24.0,<0.25"
libcurl = "8.9.1.*"
