setup_config:                 # options parsed to wflow toml file <section>.<option>
  starttime: 2016-01-01T00:00:00
  endtime: 2021-01-01T00:00:00
  timestepsecs: 86400
  input.path_forcing: inmaps-era5-2016-2020.nc
  
setup_precip_forcing:
  precip_fn: era5          # source for precipitation.
  precip_clim_fn:          # source for high resolution climatology to correct precipitation if any.

setup_temp_pet_forcing:
  temp_pet_fn: era5          # source for temperature and potential evapotranspiration.
  press_correction: True          # if True temperature is corrected with elevation lapse rate.
  temp_correction: True          # if True pressure is corrected with elevation lapse rate.
  dem_forcing_fn: era5_orography # source of elevation grid corresponding to temp_pet_fn. Used for lapse rate correction.
  pet_method: debruin       # method to compute PET: {debruin, makkink}
  skip_pet: False         # if True, only temperature is prepared.
 
write_forcing: