setup_config:                 # options parsed to wflow toml file <section>.<option>
  starttime: 2020-01-01T00:00:00
  endtime: 2021-01-01T00:00:00
  timestepsecs: 86400
  input.path_forcing: inmaps-era5-2020.nc

setup_basemaps:
  hydrography_fn: merit_hydro_ihu_30sec_v1.0
  basin_index_fn: merit_hydro_index
  upscale_method: ihu
  res: 0.00833

setup_rivers:
  hydrography_fn: merit_hydro_ihu_30sec_v1.0      # source hydrography data, should correspond to hydrography_fn in setup_basemaps
  river_geom_fn: rivers_lin2019_v1 # river source data with river width and bankfull discharge
  river_upa: 30               # minimum upstream area threshold for the river map [km2]
  rivdph_method: powlaw           # method to estimate depth {'powlaw', 'manning', 'gvf'}
  min_rivdph: 1                # minimum river depth [m]
  min_rivwth: 30               # minimum river width [m]
  slope_len: 2000             # length over which tp calculate river slope [m]
  smooth_len: 5000             # length over which to smooth river depth and river width [m]
  river_routing: local-inertial   # {'kinematic-wave', 'local-inertial'}

setup_floodplains: # if 1D floodplains are required
  hydrography_fn: merit_hydro      # source hydrography data, should correspond to hydrography_fn in setup_basemaps
  floodplain_type: 1d    # If one-dimensional floodplains are required
  flood_depths: # flood depths at which a volume is derived
    - 0.5
    - 1.0
    - 1.5
    - 2.0
    - 2.5
    - 3.0
    - 4.0
    - 5.0

setup_reservoirs:
  reservoirs_fn: hydro_reservoirs  # source for reservoirs shape and attributes
  timeseries_fn: gww           # additionnal source for reservoir are timeseries to compute reservoirs, Either 'gww' using gwwapi or 'jrc' using hydroengine.
  min_area: 1.0           # minimum lake area to consider [km2]

setup_lakes:
  lakes_fn: hydro_lakes   # source for lakes based on hydroLAKES: {hydro_lakes}
  min_area: 10.0          # minimum reservoir area to consider [km2]

setup_glaciers:
  glaciers_fn: rgi           # source for glaciers based on Randolph Glacier Inventory {rgi}
  min_area: 1.0           # minimum glacier area to consider [km2]
 
setup_lulcmaps:
  lulc_fn : globcover     # source for lulc maps: {globcover, vito, corine}

setup_laimaps:
  lai_fn: modis_lai     # source for LAI: {modis_lai}

setup_soilmaps:
  soil_fn: soilgrids     # source for soilmaps: {soilgrids}
  ptf_ksatver: brakensiek    # pedotransfer function to calculate hydraulic conductivity: {brakensiek, cosby}

setup_outlets:
  river_only: True

setup_gauges:
  gauges_fn: grdc          # if not None add gaugemap. Either a path or known gauges_fn: {grdc}
  snap_to_river: True          # if True snaps gauges from source to river
  derive_subcatch: False         # if True derive subcatch map based on gauges.

setup_constant_pars:
  KsatHorFrac: 100
  Cfmax: 3.75653
  cf_soil: 0.038
  EoverR: 0.11
  InfiltCapPath: 5
  InfiltCapSoil: 600
  MaxLeakage: 0
  rootdistpar: -500
  TT: 0
  TTI: 2
  TTM: 0
  WHC: 0.1
  G_Cfmax: 5.3
  G_SIfrac: 0.002
  G_TT: 1.3