setup_config:                 # options parsed to wflow toml file <section>.<option>
  starttime: 2017-07-01T00:00:00
  endtime: 2023-07-01T00:00:00
  timestepsecs: 86400

setup_temp_pet_forcing:
  temp_pet_fn: era5_daily
  pet_method: debruin
  press_correction: True
  temp_correction: True
  dem_forcing_fn: era5_orography

#setup_precip_forcing:
#  precip_fn: era5_daily
  
#write_forcing:
#  fn_out: /p/moonshot2-casestudy/Wflow/workshop-prep/forcing_era5.nc
#  freq_out: Y
  
setup_precip_forcing:
  precip_fn: chirps_africa_daily_v2.0
  
write_forcing:
  fn_out: /p/moonshot2-casestudy/Wflow/workshop-prep/forcing_chirps.nc
  freq_out: Y