system:
  crs: "EPSG:4326"
  
files:
  basins: "data/2-interim/GIS/basins_mainland_and_madagascar.geojson"

methods:
  cluster: "domain_method"
  touches: "centroid"

wflow:
  starttime: "2010-01-01T00:00:00"
  endtime: "2018-12-31T00:00:00"
  timestep: 10800
  #running
  wflow_cfg_name: "wflow_sbm.toml"
  wflow_project_dir: "dir"
  wflow_threads: 1
