system:
  crs: "EPSG:4326"
  
data:
  basins: "data/2-interim/GIS/basins_mainland_and_madagascar.geojson"
  temp_precip_forcing: "era5_daily_zarr"
  directories:
    external: "data/1-external"
    interim: "data/2-interim"
    input: "data/3-input"
    output: "data/4-output"
  models:
    wflow: "src/3-model/wflow_build"
    sfincs_boundary: "src/3-model/update_gauges"

methods:
  cluster: "domain_method"
  touches: "centroid"
  pet_method: "penman-monteith_tdew"
  tmin: 1980
  tmax: None
  gauges: "sfincs"

wflow:
  starttime: "2010-01-01T00:00:00"
  endtime: "2018-12-31T00:00:00"
  timestep: 10800
  wflow_cfg_name: "wflow_sbm.toml"
  wflow_project_dir: "dir"
  wflow_threads: 1

# HydroMT Wflow
setup_basemaps:
  hydrography_fn: merit_hydro_ihu_30sec_v1.0
  basin_index_fn: merit_hydro_index
  upscale_method: ihu
  res: 0.00833

