"""
PUTTING ALL SNAKEMAKE EXECUTOR STUFF HERE
"""

executor: cluster-generic
# configfile: $HOME/documents/RWSoS/RWSOS_Calibration/meuse/config/calib.yml
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
restart-times: 0
forceall: False
max-jobs-per-second: 4
max-status-checks-per-second: 1
jobs: 60
rerun-triggers: mtime

#successor to --cluster must be installed with pip snakemake-executor-plugin-cluster-generic  (1.0.9)
cluster-generic-submit-cmd:
  mkdir -p /p/moonshot2-casestudy/data/0-log/h7/{name} &&
  sbatch
    --partition={resources.partition}
    --account=hyd
    --time={resources.time}
    --get-user-env
    --qos={resources.qos}sacct
    --cpus-per-task={threads}
    --job-name={name}_{jobid}
    --output=/p/moonshot2-casestudy/data/0-log/h7/{name}/{jobid}.log

#scontrol show partition 4pcpu shows unlimited mem
default-resources:
  - partition="4vcpu"
  - qos="sbatch"
  - time="10-12:00:00"
  - mem_mb=32768 #32gb

cores: 4
local-cores: 4

